### ISSUE TITLE
Mention extra parameters in documentation

### ISSUE THREAD

**Issue by ohadschn** [floatinghotpot/ipa-deploy#2]
Taking the extra arguments and feeding them to `ios-deploy` is very convenient and important, it should probably be mentioned in the README and have an example that makes use of it.

**Comment by pMaske** [comment]
@ohadschn were you able to pass extra arguments to iOS-deploy. I tried it but looks like arguments are ignored.
I have already tried following ways to pass two arguments a true and value 1968

ios-deploy --justlaunch --args "true 1968" --bundle <bundlename>
ios-deploy --justlaunch --args true 1968 --bundle <bundlename>
ios-deploy --justlaunch --args true,1968 --bundle <bundlename>

**Comment by ohadschn** [comment]
@pMaske this looks like a question for the `ios-deploy` repo. 

We are in the `ipa-deploy` repo here, and this issue that I opened merely references the fact that `ipa-deploy` passes all extra arguments to `ios-deploy` as they are:
https://github.com/floatinghotpot/ipa-deploy/blob/8e6c27b0795a549e45eee8edc915f5b43b2798ec/index.js#L33

**Comment by floatinghotpot** [comment]
ipa-deploy has been re-written with python3.
