### ISSUE TITLE
怎么解决“The identity used to sign the executable is no longer valid”？

### ISSUE THREAD

**Issue by luckypoem** [floatinghotpot/ipa-deploy#3]
hello.

我运行ipa-deploy some-app.ipa
显示：
...
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 70%] VerifyingApplication
2017-06-27 19:44:23.558 ios-deploy[11189:88154] [ !! ] Error 0xe8008018: The identity used to sign the executable is no longer valid. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
yudeMacBook-Air:downloads brite$

怎么解决“The identity used to sign the executable is no longer valid”？
谢谢你

**Comment by floatinghotpot** [comment]
这句话用谷歌翻译出来的意思是“用于签署可执行文件的身份不再有效”。

也就是说，签名打包这个ipa的数字证书已经失效，这个包已经不合法了。

**Comment by luckypoem** [comment]
不会是因为我的iPhone 没越狱造成的吧？我的iPhone 未越狱。你这个程序即使iPhone 未越狱也能把ipa 安装到iPhone 里吗？

**Comment by floatinghotpot** [comment]
也许。

以下情况不需要越狱。如果是你自己开发的APP：
1、用开发者证书（年费99美金）签名，每个证书可以最多绑定99个测试手机的UDID；
2、或者 是用企业证书（年费299美金）签名的安装包。
